### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by vendamere** [Skasselbard/nom-uri#2]
Is this project still being maintained?

It's a couple of versions behind nom and unpublished.  It looks very comprehensive and is exactly what I'm looking to use. Url doesn't fit my use case, as it's not general to all URIs.

**Comment by Skasselbard** [comment]
I accept contributions and will review pull requests. Beyond this, I will not be able to allocate enough spare time.

I started this as a side project because I needed a no std URI parser for microcontroller programming. However, I moved on to other Projects in the meantime. And unfortunately, I do not do much rust programming nowadays.

You are free to fork and publish the project if you like. Especially if you mention me.
